name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  testing:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  build:
    runs-on: ubuntu-latest
    needs: testing
    name: Build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: run test
        run: pnpm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
    name: Deploy to Package Registry
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          token: '${{ secrets.NPM_TOKEN }}'

      - name: Install dependencies
        run: pnpm install

      - name: Config Github
        run: |
          git config --global user.email "${{secrets.GIT_EMAIL}}"
          git config --global user.name "${{secrets.GIT_USER}}"

      - name: Publish to GitHub Package Registry
        run: pnpm release-ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

